#!/bin/bash

DAGSTER_CHART_VERSION=${DAGSTER_VERSION}

kind delete clusters --all

helm repo update

kind create cluster --name=dev

kind load docker-image --name=dev ${DAEMON_REPOSITORY}:${DAGSTER_VERSION}
kind load docker-image --name=dev ${ELECTOR_REPOSITORY}:amd64-${ELECTOR_VERSION}

kubectl create ns dagster

helm --namespace=dagster upgrade \
  dagster \
  dagster/dagster \
  --install \
  --version=${DAGSTER_CHART_VERSION} \
  --values=${WORKING_DIR}/deploy/dagster-values.yaml

kubectl --namespace=dagster create -f ${WORKING_DIR}/deploy/dagster-daemon.yaml
